---
project: lid_segmentation
task: cam_generation
log_path: /home/ostap/logs

device: cuda:0

train:
  path: /datasets/LID/ILSVRC/Data/DET/train/train2014.json
  transform:
    size: &SIZE 352
    augmentation_scope: strong
    images_normalization: &IMAGES_NORMALIZATION default
    images_output_format_type: &IMAGES_OUTPUT_FORMAT_TYPE float
    size_transform: resize

val:
  path: /datasets/LID/ILSVRC/Data/DET/train/val2014.json
  transform:
    size: *SIZE
    augmentation_scope: none
    images_normalization: *IMAGES_NORMALIZATION
    images_output_format_type: *IMAGES_OUTPUT_FORMAT_TYPE
    size_transform: resize

model:
  arch: resnet50
  pretrained: True
  classes: 200
  weights_path: /home/ostap/logs/cam_generation/resnet50-2020-03-05-01-22-34/model_best.h5
  loss:
    name: binary_cross_entropy
  metrics:
    - hamming
    - mlaccuracy
    - mlf1

num_epochs: 15
batch_size: 24
optimizer:
  name: adam
  lr: [0.00005, 0.00005]
  weight_decay: 0.00001

scheduler:
  name: plateau
  mode: max
  patience: 2
  factor: 0.5
  min_lr: 0.0000001

monitor:
  method: epochs
  interval: 5


